#!/bin/bash

trap ctrl_c INT
ctrl_c() {
printf "\033[1;31m

       [X]\033[0m(Ctrl+C) Detected, Trying To Exit
"; sleep 1
printf "\033[1;31m
       Good Byee...
       
"; exit
}



have() {
  if  grep -q 'deb http://http.kali.org/kali kali-rolling main contrib non-free' '/etc/apt/sources.list.backup_tb';
    then
      printf "       \033[1;31m[X]\033[0m You haven't added the repository...\n\n"
      backtohome
     else
      sudo cp /etc/apt/sources.list.backup_tb /etc/apt/sources.list
      sleep 2
      rintf "\n\n       \033[1;31mLoadning..."
      home11
      echo
      sudo apt update
      printf "\n\n       \033[1;32m[✓]\033[0m Success remove kali repository...\n\n"
      backtohome
  fi
}

checkfile() {
    if [ ! -f /etc/apt/sources.list.backup_tb ]
    then
      printf "       \033[1;31m[X]\033[0m File backup not found...\n"
      backtohome
     else
      have
    fi
}

install() {
 if grep -q 'deb http://http.kali.org/kali kali-rolling main contrib non-free' '/etc/apt/sources.list';
 then
  printf "       \033[1;31m[X]\033[0m You have added kali repository...\n\n"
  backtohome
   else
   sudo cp /etc/apt/sources.list /etc/apt/sources.list.backup_tb
   echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" | sudo tee -a /etc/apt/sources.list
   wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add
   printf "\n       \033[1;31mLoading..."; sleep 2
   home11
   echo
   sudo apt update
  printf "\n       \033[1;32m[✓]\033[0m Success added kali repository...\n\n"
  backtohome
 fi

 }

home() {
clear
printf "
                                                               \033[1;31m+--------------+\033[0m
                                                              \033[1;31m/|             /|\033[0m
   \033[1;32m ______   ___    ___   _     _____ ____    ___   __ __    \033[1;31m/ |            / |\033[0m
   \033[1;32m|      | /   \  /   \ | |   / ___/|    \  /   \ |  |  |  \033[1;31m*--+-----------*  |\033[0m
   \033[1;32m|      ||     ||     || |  (   \_ |  o  )|     ||  |  |  \033[1;31m|  |           |  |\033[0m
   \033[1;32m|_|  |_||  O  ||  O  || |___\__  ||     ||  O  ||_   _|  \033[1;31m|  |           |  |\033[0m
     \033[1;32m|  |  |     ||     ||     /  \ ||  O  ||     ||     |  \033[1;31m|  |           |  |\033[0m
     \033[1;32m|  |  |     ||     ||     \    ||     ||     ||  |  |  \033[1;31m|  +-----------+--+\033[0m
     \033[1;32m|__|   \___/  \___/ |_____|\___||_____| \___/ |__|__|  \033[1;31m| /            | /\033[0m
       \033[0m<\033[1;36m\033[0;96m-\033[1;31m=\033[0;96m--\033[1;31m===\033[1;36m-\033[1;31m===\033[1;36m--\033[1;31m[\033[0m Author: zidansec \033[1;31m]\033[1;36m--\033[1;31m===\033[1;36m-\033[1;31m===\033[1;36m--\033[1;31m=\033[1;36m-\033[0m>     \033[1;31m|/             |/  \033[4;31mV.01\033[0m
                                                            \033[1;31m*--------------*  \033[0m"
inpts
}

hometools() {
clear
printf "
                                                               \033[1;31m+--------------+\033[0m
                                                              \033[1;31m/|             /|\033[0m
   \033[1;32m ______   ___    ___   _     _____ ____    ___   __ __    \033[1;31m/ |            / |\033[0m
   \033[1;32m|      | /   \  /   \ | |   / ___/|    \  /   \ |  |  |  \033[1;31m*--+-----------*  |\033[0m
   \033[1;32m|      ||     ||     || |  (   \_ |  o  )|     ||  |  |  \033[1;31m|  |           |  |\033[0m
   \033[1;32m|_|  |_||  O  ||  O  || |___\__  ||     ||  O  ||_   _|  \033[1;31m|  |           |  |\033[0m
     \033[1;32m|  |  |     ||     ||     /  \ ||  O  ||     ||     |  \033[1;31m|  |           |  |\033[0m
     \033[1;32m|  |  |     ||     ||     \    ||     ||     ||  |  |  \033[1;31m|  +-----------+--+\033[0m
     \033[1;32m|__|   \___/  \___/ |_____|\___||_____| \___/ |__|__|  \033[1;31m| /            | /\033[0m
       \033[0m<\033[1;36m\033[0;96m-\033[1;31m=\033[0;96m--\033[1;31m===\033[1;36m-\033[1;31m===\033[1;36m--\033[1;31m[\033[0m Author: zidansec \033[1;31m]\033[1;36m--\033[1;31m===\033[1;36m-\033[1;31m===\033[1;36m--\033[1;31m=\033[1;36m-\033[0m>     \033[1;31m|/             |/  \033[4;31mV.01\033[0m
                                                            \033[1;31m*--------------*  \033[0m"
inptstools
}

home11() {
clear
printf "
                                                               \033[1;31m+--------------+\033[0m
                                                              \033[1;31m/|             /|\033[0m
   \033[1;32m ______   ___    ___   _     _____ ____    ___   __ __    \033[1;31m/ |            / |\033[0m
   \033[1;32m|      | /   \  /   \ | |   / ___/|    \  /   \ |  |  |  \033[1;31m*--+-----------*  |\033[0m
   \033[1;32m|      ||     ||     || |  (   \_ |  o  )|     ||  |  |  \033[1;31m|  |           |  |\033[0m
   \033[1;32m|_|  |_||  O  ||  O  || |___\__  ||     ||  O  ||_   _|  \033[1;31m|  |           |  |\033[0m
     \033[1;32m|  |  |     ||     ||     /  \ ||  O  ||     ||     |  \033[1;31m|  |           |  |\033[0m
     \033[1;32m|  |  |     ||     ||     \    ||     ||     ||  |  |  \033[1;31m|  +-----------+--+\033[0m
     \033[1;32m|__|   \___/  \___/ |_____|\___||_____| \___/ |__|__|  \033[1;31m| /            | /\033[0m
       \033[0m<\033[1;36m\033[0;96m-\033[1;31m=\033[0;96m--\033[1;31m===\033[1;36m-\033[1;31m===\033[1;36m--\033[1;31m[\033[0m Author: zidansec \033[1;31m]\033[1;36m--\033[1;31m===\033[1;36m-\033[1;31m===\033[1;36m--\033[1;31m=\033[1;36m-\033[0m>     \033[1;31m|/             |/  \033[4;31mV.01\033[0m
                                                            \033[1;31m*--------------*  \033[0m"

}

inpts() {
printf "
       01\033[1;33m)\033[1;32m Add Kali Repository & Update\033[0m
       02\033[1;33m)\033[1;32m Remove Kali Repository\033[0m
       03\033[1;33m)\033[1;32m Install Top 15 Tools\033[0m

       00\033[1;33m)\033[1;36m Exit

       \033[1;31m[\033[1;33m+\033[1;31m]\033[1;32m> \033[0m"; read inpts
if [ ! -f $inpts ]
then
echo
else
printf "
       \033[1;31m
       Wrong Input... 
"; sleep 1
clear
home
fi

if [ $inpts = "0" ] || [ $inpts = "00" ]
then
printf "\033[1;31m
       Good Byee...
       
"; sleep 2
exit
fi

if [ $inpts = "exit" ] || [ $inpts = "Exit" ]
then
printf "\033[1;31m
       Good Byee...
       
"; sleep 2
exit
fi

if [ $inpts = "1" ] || [ $inpts = "01" ]
then
install
backtohome
fi

if [ $inpts = "2" ] || [ $inpts = "02" ]
then
checkfile
backtohome
fi

if [ $inpts = "3" ] || [ $inpts = "03" ]
then
hometools
fi

if [ $inpts = "h" ] || [ $inpts = "help" ]
then
home11
printf "\033[0m
  This tool serves to add the kali linux repository to the ubuntu repository instantly.
  So that ubuntu users can install some of the tools that exist on kali linux.

  You can install some packages manually
   Example: $ sudo apt install \033[10;95m<pkg>\033[0m
                               \033[10;95msqlmap\033[0m
                               \033[10;95mnmap\033[0m


  Visit the website below to see what tools you can install

  https://www.kali.org/tools/
";
backhh
fi

if [ ! $inpts ]
then
echo
else
printf "
       \033[1;31m
       Wrong Input... 
"; sleep 1
clear
home
fi

}

inptstools() {
printf "
       01\033[1;33m)\033[1;32m Metasploit\033[0m     06\033[1;33m)\033[1;32m WhatWeb\033[0m     11\033[1;33m)\033[1;32m Dirsearch\033[0m
       02\033[1;33m)\033[1;32m Sublist3r\033[0m      07\033[1;33m)\033[1;32m WafW00f\033[0m     12\033[1;33m)\033[1;32m ExploitDB\033[0m
       03\033[1;33m)\033[1;32m Bettercap\033[0m      08\033[1;33m)\033[1;32m WPScan\033[0m      13\033[1;33m)\033[1;32m Joomscan\033[0m
       04\033[1;33m)\033[1;32m Weevely\033[0m        09\033[1;33m)\033[1;32m Sqlmap\033[0m      14\033[1;33m)\033[1;32m OScanner\033[0m
       05\033[1;33m)\033[1;32m DNSenum\033[0m        10\033[1;33m)\033[1;32m Nmap\033[0m        15\033[1;33m)\033[1;32m Nikto\033[0m

       99\033[1;33m)\033[1;36m Help\033[0m
       00\033[1;33m)\033[1;36m Back

       \033[1;31m[\033[1;33m+\033[1;31m]\033[1;32m> \033[0m"; read inptstools
if [ ! -f $inptstools ]
then
echo
else
printf "
       \033[1;31m
       Wrong Input... 
"; sleep 1
clear
hometools
fi

if [ $inptstools = "0" ] || [ $inptstools = "00" ]
then
home
fi

if [ $inptstools = "exit" ] || [ $inptstools = "Exit" ]
then
printf "\033[1;31m
       Good Byee...
       
"; sleep 2
exit
fi

if [ $inptstools = "1" ] || [ $inptstools = "01" ]
then
clear
sudo apt install metasploit-framework
backtohometools
fi

if [ $inptstools = "2" ] || [ $inptstools = "02" ]
then
clear
sudo apt install sublilist3r
backtohometools
fi

if [ $inptstools = "3" ] || [ $inptstools = "03" ]
then
clear
sudo apt install bettercap
backtohometools
fi

if [ $inptstools = "4" ] || [ $inptstools = "04" ]
then
clear
sudo apt install weevely
backtohometools
fi

if [ $inptstools = "5" ] || [ $inptstools = "05" ]
then
clear
sudo apt install dnsenum
backtohometools
fi

if [ $inptstools = "6" ] || [ $inptstools = "06" ]
then
clear
sudo apt install whatweb
backtohometools
fi

if [ $inptstools = "7" ] || [ $inptstools = "07" ]
then
clear
sudo apt install wafw00f
backtohometools
fi

if [ $inptstools = "8" ] || [ $inptstools = "08" ]
then
clear
sudo apt install wpscan
backtohometools
fi

if [ $inptstools = "9" ] || [ $inptstools = "09" ]
then
clear
sudo apt install sqlmap 
backtohometools
fi

if [ $inptstools = "10" ] || [ $inptstools = "10" ]
then
clear
sudo apt install nmap 
backtohometools
fi

if [ $inptstools = "11" ] || [ $inptstools = "11" ]
then
clear
sudo apt install dirsearch 
backtohometools
fi

if [ $inptstools = "12" ] || [ $inptstools = "12" ]
then
clear
sudo apt install exploitdb 
backtohometools
fi

if [ $inptstools = "13" ] || [ $inptstools = "13" ]
then
clear
sudo apt install joomscan 
backtohometools
fi

if [ $inptstools = "14" ] || [ $inptstools = "14" ]
then
clear
sudo apt install oscanner 
backtohometools
fi

if [ $inptstools = "15" ] || [ $inptstools = "15" ]
then
clear
sudo apt nikto 
backtohometools
fi

if [ $inptstools = "99" ] || [ $inptstools = "help" ]
then
home11
printf "\033[0m
  This tool serves to add the kali linux repository to the ubuntu repository instantly.
  So that ubuntu users can install some of the tools that exist on kali linux.

  You can install some packages manually
   Example: $ sudo apt install \033[10;95m<pkg>\033[0m
                               \033[10;95msqlmap\033[0m
                               \033[10;95mnmap\033[0m


  Visit the website below to see what tools you can install

  https://www.kali.org/tools/
";
back99
fi

if [ ! $inptstools ]
then
echo
else
printf "
       \033[1;31m
       Wrong Input... 
"; sleep 1
clear
hometools
fi

}

backtohome() {
printf "\033[1;33m
       Click enter to return to the main menu \033[1;31m[\033[1;32m*\033[1;31m]\033[0m  ";read menutes
if [ $menutes == "$menutes" ]
then
home
else
home
fi
}

backtohometools() {
printf "\033[1;33m
       Click enter to return to the main menu \033[1;31m[\033[1;32m*\033[1;31m]\033[0m  ";read menutes
if [ $menutes == "$menutes" ]
then
hometools
else
hometools
fi
}

back99() {
printf "\033[1;33m
  Click enter to return to the main menu \033[1;31m[\033[1;32m*\033[1;31m]\033[0m  ";read menutes
if [ $menutes == "$menutes" ]
then
hometools
else
hometools
fi
}

backhh() {
printf "\033[1;33m
  Click enter to return to the main menu \033[1;31m[\033[1;32m*\033[1;31m]\033[0m  ";read menutes
if [ $menutes == "$menutes" ]
then
home
else
home
fi
}

home